### ISSUE TITLE
The exitstatus property is always 0 after running a powershell script

### ISSUE THREAD

**Issue by ghost** [ebsco/mixlibrary-core#1]
Hello,

I was put onto this Mixin by @brendonmartino and @carpnick.  I have implemented a Chef LWRP with it to execute a PowerShell script and get back the exit code from the script.  I am calling the resource with a script that in the end issues an `exit -50` because I am not sending in the required parameters.

I know from the log file that this script produces it is indeed getting called and is running correctly given the input that I am producing.  I have verified that the exit code is indeed -50 but the exitstatus property is always 0.

Just to make sure I changed the `exit` statement in my PowerShell script to be a `return` statement and that did not change anything...still getting an exitstatus of 0.

My system has v0.0.5 of the gem installed.

I am hoping that someone can help figure our what is wrong.

Thank you,
Eric

Here is my resource

``` ruby
actions :run
default_action :run 

attribute :name, :name_attribute => true
attribute :code, :kind_of => String, :default => ""
attribute :returns, :kind_of => Array, :default => []
attribute :cwd, :kind_of => String, :default => ""
```

Here is my provider

``` ruby
use_inline_resources
def lazy_load
    # This sets up the mixlib windows_script_out...we need to delay this load until the gem can be installed...
    require 'mixlibrary/core/apps/shell'
end

def whyrun_supported?
  true
end

action :run do

    success = false
    Chef::Log.info "Starting"
    converge_by("Run #{@new_resource}") do
        # to delay the mixlibrary gem reference until the default recipe can install it...
        lazy_load

        Chef::Log.info "Running this code: '#{@current_resource.code}'"
        # get the result object (and exit code) from the above code execution:    
        # :powershell is the type of script and the var holds all the code. This is how to properly call the gems function and get the exit code from the object it returns
        Dir.chdir(@current_resource.cwd)
        result = Mixlibrary::Core::Shell.windows_script_out(:powershell, @current_resource.code)

        Chef::Log.info "Finished Running: #{result.exitstatus}"
        if (0 == result.exitstatus)
            @success = true
            Chef::Log.info "#{ @new_resource } succeeded."
        elsif (@current_resource.returns.include? result.exitstatus) 
            @success = true
            Chef::Log.warn "#{ @new_resource } generated a warning message."
        else
            @success = false
            Chef::Log.error "#{ @new_resource } failed to execute."
        end
        Chef::Log.info "Ending"
    end
    success
end

def load_current_resource
    @current_resource = Chef::Resource::RstPowershellAutomationGehcpowershellscript.new(new_resource.name)
    @current_resource.name(new_resource.name)
    @current_resource.code(new_resource.code)
    if new_resource.cwd.empty?
        @current_resource.cwd(Dir.pwd)
    else
        @current_resource.cwd(new_resource.cwd)
    end
    @current_resource.returns(new_resource.returns)
end
```

Here is a snippet from the Chef output that contains the output from my LWRP

```
[2015-01-16T14:52:57-06:00] INFO: Starting
[2015-01-16T14:52:57-06:00] INFO: Running this code: '.\UView_Add_Update_CPACS_Entities.ps1 -Silent -SybaseSApwd ""'
[2015-01-16T14:52:58-06:00] INFO: Finished Running: 0
[2015-01-16T14:52:58-06:00] INFO: rst-powershell-automation_gehcpowershellscript[UView_Add_Update_CPACS_Entities] succeeded.
[2015-01-16T14:52:58-06:00] INFO: Ending

    - Run rst-powershell-automation_gehcpowershellscript[UView_Add_Update_CPACS_Entities]
```

**Comment by carpnick** [comment]
I think maybe your problem is the current working directory might not be what you expect.  I see you referring to the script to execute as local directory.  Because powershell, by default returns an exit code of 0, it is hard to debug with.

Try printing out stdout and stderror - that might help here:
Chef::Log.info "Standard Out: #{result.stdout}"
Chef::Log.info "Standard Error: #{result.stderr}"

**Comment by brendonmartino** [comment]
Well, for starters you should be doing your lazy_load in load_current_resource, not the action block. If you look more closely at my example, you will see that I have done it that way.

Also, I have no idea what @current_resource.code looks like -- I can only assume it is a legit ps script that returns zero if successful. If I were you, I would make it return something non-standard, random, say, 42. Then you can do a printout (Chef::Log) statement to see what code you are getting on exit. Make your ps script robust by returning some default error code (say, 95 for example) if it doesn't succeed.  

Then you will be able to see if it is working as expected or not.

**Comment by ghost** [comment]
@brendonmartino @current_resource.code is legit, (see the chef output below for the exact code)
and it has about 50 possible return codes depending on the circumstances.  0 means success, a negative number means an error and a positive number is a warning.  

Like I said in my original post the code that is being passed in is being called and it is working.  It generates a log file that is unrelated to Chef, and that log file is getting generated.  The content of the log file is what I would expect given the parameters that I am sending it.

As for return value, because of the way I am calling the PS script it generates an error exit code of -50, which in the case of my script means that I have not provided some required parameter values. 

I do have several Chef::Log statements in my provider which print this out with the rest of the converge output:

```
[2015-01-16T14:52:57-06:00] INFO: Starting
[2015-01-16T14:52:57-06:00] INFO: Running this code: '.\UView_Add_Update_CPACS_Entities.ps1 -Silent -SybaseSApwd ""'
[2015-01-16T14:52:58-06:00] INFO: Finished Running: 0
[2015-01-16T14:52:58-06:00] INFO: rst-powershell-automation_gehcpowershellscript[UView_Add_Update_CPACS_Entities] succeeded.
[2015-01-16T14:52:58-06:00] INFO: Ending
```

The line `Finished Running: 0` is from a logging call that prints out the exitstatus property on the object returned from the mixin.  I have run the script so that it generates a positive number, a negative number and I have set the exit code to various constant values.  I have also switched froom using the `exit` command to using a `return` statement.  However in all cases the exitstatus property is always zero.

@carpnick, the working directory is exactly what I expect it to be.  The log file that I mentioned above gets placed in the folder where the script is started from.  When I run the converge the log file is saved in the folder that I am intending to be the current working folder, so as far as I can tell it is running the script from the correct location with the correct working folder.

The mixin seems to be running my PowerShell code correctly it is just not getting the exit code back to me.  If it is helpful I can package up an whole cookbook and upload it so that you can run and see if you get the same thing in your environment.  Good idea?  Bad idea?

I will add stdout and stderr to the script and see if it provides anything informative.

Thanks for the input, other ideas you may have would be helpful.

Eric

**Comment by carpnick** [comment]
I had a long response on how you should be using something else to exit powershell.  But I think you hit a use case we didn't test for at the end of the day.

We were expecting most use cases to be exiting directly within the  EOH block of powershell code not in sub powershell scripts.

Either way I went ahead and created what I consider a valid [test case](https://github.com/ebsco/mixlibrary-core/blob/master/test/powershell.rb#L63) for this case and released a 0.0.7 for you.

I think this should fix it for you.

Additional information: How does exit/return/break work.  This Stackoverflow article sums it up pretty well: http://stackoverflow.com/a/23703056

**Comment by carpnick** [comment]
Keeping issue open until you validate.

**Comment by ghost** [comment]
@carpnick, Thank you for this.  I will test it this morning and let you know the results.

**Comment by ghost** [comment]
OK, so I seem to be mostly there.  I have one problem and one interesting thing that I have found out.

## The problem

If I do an exit in my child PowerShell script then the exit code is getting converted to an unsigned integer.  Is this the intended design or a bug?

Our return codes are classified as follows so it would be great if I can get a signed integer back:
0 = Success
Positive numbers = Warnings
Negative numbers = Errors

## The interesting thing

How I specify the code makes a difference in success or failure
If I specify my code as a string the mixin does not return the result code...only 0

```
rst_powershell_automation_gehcpowershellscript scriptName do
    action :run
    name scriptName
    cwd "#{commonParameters['rst_package_path']}#{commonParameters['rst_package_path_uview']}"
    code ".\\#{scriptName}.ps1 -Silent#{scriptParameterString}"
    returns [0, -50]
end
```

On the other hand if I use an EOH block then I do get the return value.

```
rst_powershell_automation_gehcpowershellscript scriptName do
    action :run
    name scriptName
    cwd "#{commonParameters['rst_package_path']}#{commonParameters['rst_package_path_uview']}"
    code <<-EOH
    .\\#{scriptName}.ps1 -Silent#{scriptParameterString}
    EOH
    returns [0, -50]
end
```

**Comment by ghost** [comment]
FYI, I have figured out a work-around for the problem identified above.  I created a method that will convert an unsigned integer to a signed integer.  It needs to make some assumptions about the bit-depth of the original return code, so it would still be better from my perspective if this conversion never happened in the first place.

**Comment by carpnick** [comment]
# The unsigned integer

Not a bug in any shape or form.  Kind of how powershell works.  Lets take an example script that exits with -1.  I created a script called test.ps1.  The only line it has in it is "exit -1".  Now from a command prompt I am going to  call that file.  See below output:

```
>powershell -File C:\test.ps1
>echo %ERRORLEVEL%
65535
```

Is it possible to fix.  Yes.  Changed the code to the following instead of the exit line in the script:

```
function exit-powershell([int] $exitcode){
     [Environment]::Exit($exitcode)
}

 exit-powershell -1
```

Now when we run we see the following:

```
>powershell -File C:\test.ps1
>echo %ERRORLEVEL%
-1
```

Why the difference?  Under the covers powershell is a .NET process.  And the "exit" command is a very special, pretty much undocumented command.  It works great within the powershell script, but not so much with integration frameworks on the outside.  So I have created that function above and I dot-source it with all my scripts.

# Issue 2 - EOH vs string.

I personally never tested with anything but an EOH,  Would be worth a futher look.  I will create a second issue to discuss that one.

**Comment by ghost** [comment]
Ah ... when we test our PowerShell scripts we are testing them from inside of Powershell, and there I get the result code from $LastExitCode not %ERRORLEVEL%.  Makes perfect sense now.

**Comment by ghost** [comment]
As far as I am concerned this issue can be closed.  Our LWRP is working fine.  Yes it would be good to have the flexibility to use a string for our one-liner scripts and not an EOH block, but that is a minor issue.

**Comment by carpnick** [comment]
From a ruby perspective everything is going through Shell_out.  So the default shell currently is cmd.  That means whatever exit powershell is returning cmd is returning to the shell_out command.  I, like you, wrote a rather large powershell framework at one time, and had this same problem.  What is most concerning with the exit code issue, is why does this matter?  Why do they update last exit code successfully, but dont exit the process the same way?

Either way - this one little function saves the day.  The only difference is it terminates the process.  So if testing within powershell, make sure to open a sub-powershell instance within it, otherwise your shell will disappear.
